const truthList = [
  "What's the most embarrassing thing you've ever done?",
  "Have you ever lied to your best friend, and about what?",
  "What's your biggest fear?",
  "What's the craziest thing you've ever done?",
  "Have you ever thought about being intimate with your sex?",
  "Have you tried to make out with the same sex",
"Which cartoon character would your partner be?",
"If you could travel back in time, what time period would you go to as a couple?",
"What Disney couple do you think you are the most similar to, and why?",
"Who would you rather have your children look like you or your partner?",
"You've got a free pass! If you could go on a date with any celebrity, who would it be?",
"If you were given a lifetime supply of anything of your choosing to make your relationship smooth, what would it be?",
"Which partners hogs the bed the most?",
"What is the worst meal your partner has cooked?",
"Share a phrase you both say.",
"Of all the people you know, who would you least like to see successful?",
"If you were given three wishes, what are they?",
"What is a luxury item you wish you could have but will probably not be able to afford?",
"How would you celebrate your spouse's next birthday if money wasn't a problem?",
"If you could pick a new last name for you both what would it be?",
"What are three things you adore about your partner?",
"Finish the sentence; a perfect spouse is one who ___?",
"Who is better looking, you or your partner?",
"What is your most cherished childhood memory?",
"What is your nickname for your partner?",
"What was the worst phase of your life?",
"If you could get rid of one law, what would it be?",
"When during your life have you felt the most alive?",
"What is the most humiliating thing to have happened to you?",
"Describe your dream home.",
"What would it be if you had only one movie to watch for the rest of your life?",
"Do you prefer your partner to make you breakfast, lunch, or dinner?",
"If you were given the opportunity to travel anywhere in the world for free, where would you go and why?",
"If you could pick a friend to switch lives with, who would you pick, and why?",
"If you were to have children would you prefer all girls or all boys?",
"Could you live in a tiny house or an RV for a year?",
"What is the oddest food combination you have ever eaten or would like to try?",
"What would be something you would do if you were elected president?",
"What is the best thing about being married to your partner?",
"Is there a dish your husband makes that you don't like?",
"What are three countries you would like to visit in the next five years?",
"Is there a holiday that you could live without?",
"What is your biggest fear, and why?",
"What is the most outrageous thing you've ever done?",
"Do you judge people by how they dress?",
"What has been the highest point in your life so far?",
"Describe a guilty pleasure your spouse doesn't know about.",
"What is the biggest struggle you have overcome?",
"Is there anything that you have done in the past that you wish you could do over?",
"Does your partner have any traits or annoying habits you wish you could change?",
"What would break your heart?",
"What is the wildest thing you have done on vacation, and would you do it again?",
"Is there something legal that you feel should be illegal?",
"What is something you have always wished you could do but have never gotten around to?",
"If you were given the chance to spend the day with any famous person, who would it be and why?",
"What is the biggest age difference between you and the girl/guy you've slept with?",
"What was the weirdest thing you did during a first date?",
"Have you ever sent provocative texts to anyone?",
"Have you ever wanted to do it with someone you would never want to date?",
"Is the sex better if you're in love, or is it better if the other person is hot and knows what they are doing?",
"Have you ever accidentally sent spicy pictures to the wrong person?",
"Have you tried to make out with the same sex because of a dare?",
"Could you describe the sexiest outfit you've ever owned?",
"Suppose you wake up the opposite sex tomorrow. What dirty things would you be doing all day?",
"Do you have any sex toys?",
"What X-rated movie have you watched more than once?",
"Storytime - What is your most embarrassing story in the bedroom? Or the funniest sexual experience story?",
"What do you say is your least favorite sexual position, and why?",
"What do you remember about your sexual awakening?",
"Have you ever regretted sleeping with someone right after you finished?",
"Have you had sex with someone ten years younger or older than you?",
"How often are you watching porn in a day? Have you ever paid to watch porn videos before?",
"Could you describe in detail your hottest sex dream?",
"Have you ever made out with more than one person from the same family?",
"Have you ever had any kind of same-gender experience? How about a secret fantasy about your best friend?",
"Care to share the last time you had a one-night stand?",
"When was the last time you touched yourself?",
"Have you ever had sex with someone even before you kissed them?",
"Have you ever dominated someone? Submitted to someone?",
"What do you say is the hottest thing about oral sex, giving it or receiving it?",
"Have you ever fantasized about a same-sex experience?",
"Care to share the last time that you cheated on your significant other?",
"If you can only do one sexual act for the rest of your life, would it be romantic sex or angry sex?",
"Have you ever been cuffed? And if you haven't, would you be willing to try it?",
"What was the last adult movie you watched?",
"Who do you most want to sleep without of everyone in the room?",
"If you could have someone in the room tie you up and do incredibly naughty things to you, who would you want it to be?",
"Have you ever tried anal sex?",
"If you have a chance to have a threesome with two other people in this room, who would you pick and why?",
"Have you ever had a threesome?",
"Have you ever tried making a sex tape?",
" What is your “I'm getting laid tonight” outfit?",
" How do you like me to kiss you?",
" Suppose you're a flirt expert. What tips would you give me if I want to turn you on?",
" How does it feel when I kiss your neck?",
" What is your favorite sexual memory?",
" How was your first sexual experience?",
" Would you take a shower with me if I can't promise to keep my hands to myself?",
" How long have you gone without having sex?",
" Have you ever thought about me naked in the shower?",
" What is your craziest sexual fantasy?",
" How many people have you slept with?",
" Have you ever tried having sex blindfolded? And if you haven't, would you be willing to try it with me?",
" Who's the hottest person in your workplace?",
" Which one would you prefer more, lights on or off during sex?",
" What first came to your mind the first time you saw me naked?",
" Would you ever sit and watch a steamy adult movie with me?",
" Do you like listening to music while doing it?",
" What is number one on your sexual bucket list right now?",
" Have you ever tried copping a feel whenever we hug?",
" What is your favorite message I sent you while we were sexting and why?",
" What do you think is the sexiest part of my body?",
" Have you ever faked an orgasm?",
" If you were to create an original adult movie, what would you call it?",
" Have you ever tried using a sex toy? If yes, what kind is it?",
" Which turns you on more? A foot massage, or your hair being stroked?",
" Have you ever touched yourself in a public place? If yes, what made you do it?",
" Have you ever had a one-night stand with someone else?",
" Have you had more than one partner at one time? Would you ever do a threesome with my permission?",
" Would you ever watch me sleeping with someone else?",
" If you could pick one other person to join us in the bedroom, who would you pick?",
" Have you ever thought of doing it with someone other than me?",
" Do you like foreplay? If yes, what kind of foreplay do you enjoy the most?",
" What do you think is better; make-up sex or angry sex?",
" What fantasy do you imagine whenever you touch yourself?",
" If I were handcuffed to the bed right now, could you describe in detail what naughty things you would like to do to me?",
" How often do you touch yourself?",
" What was the raunchiest, kinkiest thing you've ever done in the bedroom? What about outside of the bedroom?",
" If you were to create an original adult movie, who would you want to do it with?",
" Does dirty talk get you aroused?",
" What kind of sexual roleplaying have you tried doing before?",
" Would you ever take part in the swinger's club?",
" Could you describe the most satisfying orgasm you've ever had? And who gave it to you?",
" Have you gone to a strip club or a burlesque club?",
" If you could only pick one for the next month, which would you choose, tongue or fingers?",
" If I give you a free pass to hook up with someone else, who would you want it to be?",
" Have you ever visited a sex club? Would you consider going if I ever invited you?",
" Have you ever had an exciting dream with someone else? What was it all about?",
" Have you ever had sex in a hot tub? If not, would you want to give it a try sometime?",
" Do you prefer make-up sex to be sensual or rough, and why?",
" What is the sluttiest/nastiest thing you've always wanted to do but never have?",
" For you, does size really matter?",
" What is the most public place you've done it?",
" What is your funniest one-night stand story?",
" Have you ever been caught in action? If so, by who?",
" Have you ever cheated?",
" What is your “most adventurous” bedroom experience, and with whom?",
" What would you rather have: angry sex or makeup sex?",
" Read one of your sexts in the group.",
" How many selfies have you taken while getting busy?",
" How often do you watch something naughty?",
" What is your secret fetish? Or a guilty pleasure?",
" Have you ever faked an orgasm? With whom?",
" What is the naughtiest fantasy you'd want someone to do with you?",
" What is the dumbest thing that comes to mind that you've ever done in the bedroom?",
"oesn't have to be in 'the bedroom,' though!",
" What are the three things on your sexual bucket list?",
" How would you describe sex with the last person you slept with?",
" What is the weirdest thing somebody has ever asked you to do in the bedroom?",
" Have you ever imagined having sex with your best friend?",
"ted Reading: Questions to Ask a Guy",
" What is your biggest pet peeve or turn-off in the bedroom?",
" What is the weirdest place you've ever been naughty with someone?",
" Have you ever given or been given 'attention' while driving a car?",
" What was the last spicy photo or video you sent someone?",
" Who was the last person you sent nudes to?",
" What is that one thing that embarrassingly turns you on?",
" Have you ever done it with people around but without them knowing?",
" Have you ever done it in a movie theater?",
" What is your go to song for getting in the mood?",
" Who do you think is the sexiest person in the group?",
];

const dareList = [
  "Sing a song in public",
  "Do a handstand for 10 seconds",
  "Tell a joke in wear something that your partner wants ones a silly voice",
  "Eat something sweet from your partner's privets",
  "Wear something that your partner Wants",
  "Describe in detail your first kiss.",
"Treat the person to your right to a lap dance without touching them or them touching you.",
"Close your eyes and swipe right on your dating app a dozen times.",
"Make out with a pillow for the next 15 seconds. And don't forget to do it as you mean it!",
"Describe in detail the most embarrassing thing that happened to you in the bedroom that you haven't ever shared before.",
"Send a peach or eggplant emoji to the first person on your contact list with no further explanation.",
"Do a pole dance performance in the middle of the room. Whether there's a pole in the room or not doesn't really matter!",
"Swap shirts with anybody in the room.",
"Dance seductively to Right Said Fred's “I'm Too Sexy.”",
"Give anyone in the room a one-minute head massage.",
"Give anyone in the room a one-minute back massage.",
"Have someone post a suggestive Facebook status for you.",
"Give anyone in the room a one-minute butt massage.",
"Give someone a kiss on your favorite body part of the opposite gender.",
"Let someone from the group take charge of your dating profile for the next ten minutes.",
"Turn on a sexy song and grind up against a chair for the next 30 seconds.",
"Get into the hot tub or the shower with all your clothes on.",
"Have someone post an embarrassing picture of you on social media.",
"Take off your shirt for the remainder of the game.",
"Call your partner's parents and tell them how in love you are with their son/daughter while someone is making fart sounds in the background",
"Have someone tickle you for 15 seconds.",
"Get a banana and seductively eat it while locking eyes with the person to your left.",
"Close your eyes, and then everyone pours a shot. Open your eyes and drink one of the shots that were poured. Whoever poured the shot you just drank, you have to sit on their lap for the rest of the game.",
"Pick up one object nearest to you and, in great detail, demonstrate how to put on protection.",
"Drop several ice cubes in your pants.",
"Spin the bottle and make out with anyone it lands on.",
"Perform a convincing reenactment of the first time you had sex.",
"Do a dramatic reading of a chosen sex scene from an erotica book.",
"Make your best impression of a porno that involves a fireman in a bachelorette party (or the reverse if you're a guy).",
"Feed someone grapes with just your mouth.",
"Get a marker and have someone in the room draw a tattoo of their choice on your butt.",
"Do a body shot of [insert someone else's name but get their consent first].",
"Try to turn on a random person in the room by only using your seductive voice. No touching necessary!",
"Hold an ice cube between your front teeth and trace it along [insert consenting person in the group]'s chest.",
"Do a striptease for the entire group.",
"Lick chocolate sauce or whipped cream off someone's [insert body part].",
"Give someone in the room a full body massage.",
"Do as many sit-ups as you can while kissing the person holding your leg.",
"Lick another person's neck without touching them with any other part of your body.",
"Choose someone to demonstrate your favorite sex position.",
"You have to keep your hand on the very inner thigh of the person sitting next to you until the next round.",
"Name the most boring person in the room and make out with them.",
"Look someone in the eyes and tell them a naughty story. Don't forget to use your seductive voice!",
"Trace your fingers over someone else's lips and say “just a silly boy” in your most seductive voice.",
"If there's a swimming pool or beach nearby, you have to go skinny dipping.",
"Turn off the lights and turn on the person to your right by only using your voice.",
" Treat me to a scalp massage for five minutes while I lay my head on your lap.",
" Create a sexy playlist to use the next time you're going to hook up.",
" Do your sexiest dance performance.",
" Feed me something tasty using only your mouth.",
" Take off your partner's shirt using only your teeth. No cheating!",
" Let's take a shower together and continue the game afterward.",
" Pick up three props in the room and use them to model for an intimate, sexy, for-my-eyes-only kind of photoshoot.",
" Put one of your hands in my pants for the rest of the round.",
" Get closer to me and whisper the cheesiest, corniest pick-up line you can think of.",
" Let me handcuff/bind you to bed and tickle you.",
" Drink a shot from my belly button.",
" Try to elevate your significant other's heart rate by attempting a sultry dance to the song of their choosing. No touching with your hands!",
" You have to lick your partner's feet like you really mean it.",
" Pick a non-obvious body part (fingers, toes, etc.) of the one to your right, and lick it in the most sensual way possible.",
" Show me a toy on the internet that you are curious about and want to use, and we're going to buy it.",
" Eat something off of my chest.",
" Let me lick your lips and try to resist touching or kissing me the entire time. If you fail, then you get to do another dirty dare.",
" Lick (or suck) your significant other's nipples.",
" Let me play using an ice cube on your belly button.",
" Call one of your friends and talk about one of our bedroom adventures and how much you liked it while I'm listening in.",
" Go commando for the rest of the day or night.",
" Suck on my fingers while pretending that you are performing oral sex for the next 30 seconds.",
" Raid your closet and put together (and change) into the sexiest outfit you can find.",
" Let me raid your closet and wear any sexy outfit I can put together for you.",
" Give me a slow passionate kiss for a full minute. (If you want to make out for a full five minutes, no one is saying no!)",
" Only say yes for the next hour.",
" Lick peanut butter or whipped cream off my [insert favorite body part of your partner].",
" Play your favorite romantic song and do a sexy dance.",
" Demonstrate the sex act you've been dying to do with your partner.",
" Hide a gummy bear in any part of your body and let me find it. (Of course, it doesn't have to be a gummy bear. Any candy works, but that's not the point!)",
" Let me blindfold you and eat anything I give you.",
" Look me in the eyes and recreate the sounds you make when you make love.",
" Show me an intimate photo of yourself that I've never seen before.",
" Go to the bathroom and send me a naked snap.",
" Do a quick study of erogenous zones and give sensual massage to those areas.",
" Share your sexiest dream where you and I are the starring characters.",
" What scene from an adult movie would you like to recreate with me?",
" Let me tickle the back of your neck with an implement of my choosing!",
" Search the internet for the most sexually sensitive area of the body and arouse your partner by licking that area. No touching!",
" Let me bend you over (my knee or the couch) and spank you ten times.",
" Do your best impersonation of a hired stripper at a bachelor or bachelorette party.",
" Do any household chores while completely naked (topless or bottomless works also)!",
" Try to get yourself off by dry humping your significant other. Try doing it without touching. No kissing too!",
" Go inside the bathroom (or bedroom) and film me a form-my-eyes-only sexy movie of yourself.",
" Get yourself off while looking into my eyes and without making any sound.",
" I dare you to try out my ultimate fantasy roleplay.",
" I dare you to get naked and try out your favorite sex toy in front of me.",
" Turn off the lights and treat your partner to a handjob.",
" I dare you to give me some oral attention for at least 15 minutes or until you make me climax.",
" I dare you to find the raunchiest sexy video you have in your secret fantasy and show it to me.",
"Attempt a TikTok dance in the middle of everyone.",
"Drink a shot of any liquid chosen by anybody in the group.",
"Describe each person in the room in just one word.",
"Share your dancing chops in the middle of the group.",
"Put five ice cubes in your mouth, but you can't chew them. So just let the ice melt in your mouth!",
"Let someone draw a tattoo on your neck using a permanent marker.",
"Let someone give you a new hairstyle.",
"Eat a bite of a banana peel.",
"Serenade someone in the room.",
"Empty a glass of cold water (with ice!) on your forehead.",
"Bark like a dog for the next five minutes while the game continues.",
"Let someone in the room post a status on your social media.",
"Put a blindfold on and touch other players' faces until you can figure out who's who.",
"Read the last text you sent someone in the entire group.",
"Hand over your phone and let someone send a single text to anyone they want, saying anything they want.",
"Empty your bag to show everyone what's inside.",
"Wear another player's socks like gloves for the next ten minutes as the game continues.",
"DM your first crush on social media.",
"Put on your makeup like you usually do but without a mirror and leave it for the rest of the game.",
"Put on your best rock and roll face and play air guitar to the first song on your playlist.",
"Send a link to the last YouTube video you watched to five random friends on Facebook.",
" Share your orgasm face with everyone in the room.",
" Make eye contact with someone in the room and moan for 15 seconds.",
" Drop an ice cube inside your pants.",
" Search the dirtiest thing you can think of on the internet and show it to everyone.",
" Let another person in the room give you a back massage while you're blindfolded. If you liked it, you could kiss them afterward, but without taking off your blindfold yet!",
" Read aloud the flirtiest DM you ever sent someone or sent to you.",
" Suggest to your boyfriend/girlfriend/partner if you can bring a third person 'the next time' and record their reaction.",
" Pour your favorite drink on another player's body and slowly lick it all off.",
" Do a sexy, seductive dance in the middle of the room.",
" Demonstrate your favorite position in the bedroom.",
" Whisper the naughtiest thing you can think of to five different people in the room.",
" Demonstrate how you like to get massages in a flirty voice to another player.",
" Scroll through your contact list, but make sure you have your eyes closed, pick a random person and text them, 'I'm lonely.'",
" Text a random person with something super dirty 'accidentally.'",
" Common' feeling lonely today' in one of your crush's posts on social media.",
"'s the single best way to get your crush's attention.",
" Take a suggestive selfie with another person in the room.",
" Lightly trace your fingers over another person's lips and moan for ten seconds.",
];

const truthButton = document.getElementById("truth-button");
const dareButton = document.getElementById("dare-button");
const questionOutput = document.getElementById("question-output");

truthButton.addEventListener("click", () => {
  const randomTruth = truthList[Math.floor(Math.random() * truthList.length)];
  questionOutput.textContent = randomTruth;
});

dareButton.addEventListener("click", () => {
  const randomDare = dareList[Math.floor(Math.random() * dareList.length)];
  questionOutput.textContent = randomDare;
});

window.addEventListener('scroll', function(e) {
  if (window.scrollY <= 0) {
    // If scroll position is at the top of the page or above, allow scrolling
    document.body.style.overflowY = 'scroll';
  } else {
    // If scroll position is below the top of the page, prevent scrolling down
    document.body.style.overflowY = 'hidden';
  }